# -*- coding: utf-8 -*-
"""Python worksheet part - 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154B_icO8gnxQRRW9SPGgpVUU6eQ5jvww

**Q.11 Python program to find the factorial  of a number**
"""

def factorial_iterative(n):

    if n < 0:
        return "Factorial is not defined for negative numbers."
    elif n == 0:
        return 1
    else:
        factorial = 1
        for i in range(1, n + 1):
            factorial *= i
        return factorial

def factorial_recursive(n):

    if n < 0:
        return "Factorial is not defined for negative numbers."
    elif n == 0:
        return 1
    else:
        return n * factorial_recursive(n - 1)

num = int(input("Enter a non-negative integer: "))

method = input("Choose the method (iterative or recursive): ")

if method.lower() == "iterative":
    result = factorial_iterative(num)
elif method.lower() == "recursive":
    result = factorial_recursive(num)
else:
    print("Invalid method. Please choose 'iterative' or 'recursive'.")


print("The factorial of", num, "is", result)

"""**Q.12 Python program to find whether a number is prime or composite.**"""

import math

def is_prime(num):

    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False

    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6

    return True


num = int(input("Enter a positive integer: "))


if is_prime(num):
    print(num, "is a prime number.")
else:
    print(num, "is a composite number.")